import { Footer } from "@/Components/Footer";
import Layout from "@/Components/Layout";
import { HomeScreen } from "@/Screens/Home";
import Head from "next/head";
import { NavBar } from "../Components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Verde Lima Arquitetura</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://em-content.zobj.net/thumbs/120/apple/325/lemon_1f34b.png"
        />
      </Head>

      <Layout>
        <HomeScreen />
        <Footer />
      </Layout>
    </>
  );
}
