import { Form } from "@/Components/Form";
import { Thanks } from "@/Components/Form/ScreenThanks";
import Layout from "@/Components/Layout";
import { Contact } from "@/Screens/Contact";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Obrigado - Verde Lima Arquitetura</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://em-content.zobj.net/thumbs/120/apple/325/lemon_1f34b.png"
        />
      </Head>

      <Layout>
        <Thanks/>
      </Layout>
    </>
  );
}
